---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: git-assets

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPS_MGR_TRUSTED_CERTS:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_ZONE_1:
  GCP_ZONE_2:
  GCP_ZONE_3:
  GCP_RESOURCE_PREFIX:
  GCP_SERVICE_ACCOUNT_KEY:

run:
  path: git-assets/pcf-deployment-ci/pcf-terraform-gcp/ci/tasks/config-director/task.sh
