---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OM_DECRYPTION_PWD:

inputs:
  - name: git-assets

run:
  path: pcf-pipelines/tasks/config-opsman/task.sh
  path: git-assets/pcf-deployment-ci/pcf-terraform-gcp/ci/tasks/config-opsman/task
