resource_types:
  - name: google-cloud-storage
    type: docker-image
    source:
      repository: frodenas/gcs-resource
 
resources: 
- name: gcp-bucket
  type: google-cloud-storage
  source:
    bucket: pcf-ci-data
    versioned_file: terraform/*.json
    json_key: |
      {
        "type": "service_account",
        "project_id": {{project_id}},
        "private_key_id": {{private_key_id}},
        "private_key": {{private_key}},
        "client_email": {{client_email}},
        "client_id": {{client_id}},
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://accounts.google.com/o/oauth2/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/1051958956746-compute%40developer.gserviceaccount.com"
      }

- name: git-assets
  type: git
  source:
    branch: master
    uri: https://github.com/Logimethods/logilabs-ops.git
 
jobs:
  - name: terraform-gcp
    public: true
    plan:
      - get: git-assets
        trigger: true
      - task: terraform
        file: git-assets/pcf-deployment-ci/pcf-terraform-gcp/ci/tasks/apply-terraform.yml
        params:
          project_id: {{project_id}}
          private_key_id: {{private_key_id}}
          private_key: {{private_key}}
          client_email: {{client_email}}
          client_id: {{client_id}}
          test_key: {{test_key}}
      - put: gcp-bucket
        params: { file: git-assets/pcf-deployment-ci/pcf-terraform-gcp/ci/tasks/apply-terraform.yml }