resources: 
- name: git-assets
  type: git
  source:
    branch: master
    uri: https://github.com/Logimethods/logilabs-ops.git
 
jobs:
  - name: create-infrastructure
    public: true
    serial: true
    plan:
      - get: git-assets
        trigger: true
      - task: terraform-apply
        file: git-assets/pcf-deployment-ci/pcf-terraform-gcp/ci/tasks/apply-terraform.yml
        params:
          TF_VAR_ssl_cert: {{ssl_cert}}
          TF_VAR_ssl_cert_private_key: {{ssl_cert_private_key}}
          gs_secret_access_key: {{gs_secret_access_key}}
          gs_access_key_id: {{gs_access_key_id}}
          default_project_id: {{default_project_id}}
          action: apply
  - name: configure-opsman
    public: true
    serial: true
    plan:
      - get: git-assets
        passed:
        - create-infrastructure
      - task: config-opsman-auth
        file: git-assets/pcf-deployment-ci/pcf-terraform-gcp/ci/tasks/config-opsman/task.yml
        params:
          OM_DECRYPTION_PWD: {{pcf_opsman_admin_password}}
          OPS_MGR_PWD: {{pcf_opsman_admin_password}}
          OPS_MGR_USR: {{pcf_opsman_admin_username}}
          OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      - task: configure-director
        file: git-assets/pcf-deployment-ci/pcf-terraform-gcp/ci/tasks/config-director/task.yml
        params:
          GCP_PROJECT_ID: {{gcp_project_id}}
          GCP_REGION: {{gcp_region}}
          GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
          GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
          GCP_ZONE_1: {{gcp_zone_1}}
          GCP_ZONE_2: {{gcp_zone_2}}
          GCP_ZONE_3: {{gcp_zone_3}}
          OPS_MGR_PWD: {{pcf_opsman_admin_password}}
          OPS_MGR_TRUSTED_CERTS: {{pcf_opsman_trusted_certs}}
          OPS_MGR_USR: {{pcf_opsman_admin_username}}
          OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}           
          GCP_PROJECT_ID: {{gcp_project_id}}
          GCP_REGION: {{gcp_region}}
          GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
          GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
          GCP_ZONE_1: {{gcp_zone_1}}
          GCP_ZONE_2: {{gcp_zone_2}}
          GCP_ZONE_3: {{gcp_zone_3}}
          OPS_MGR_PWD: {{pcf_opsman_admin_password}}
          OPS_MGR_TRUSTED_CERTS: {{pcf_opsman_trusted_certs}}
          OPS_MGR_USR: {{pcf_opsman_admin_username}}
          OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}               
  - name: destroy-infrastructure
    public: true
    serial: true
    plan:
      - get: git-assets     
      - task: terraform-apply
        file: git-assets/pcf-deployment-ci/pcf-terraform-gcp/ci/tasks/apply-terraform.yml
        params:
          TF_VAR_ssl_cert: {{ssl_cert}}
          TF_VAR_ssl_cert_private_key: {{ssl_cert_private_key}}
          gs_secret_access_key: {{gs_secret_access_key}}
          gs_access_key_id: {{gs_access_key_id}}
          default_project_id: {{default_project_id}}
          action: destroy
    