resource_types:
  - name: google-cloud-storage
    type: docker-image
    source:
      repository: frodenas/gcs-resource
 
resources: 
- name: gcp-bucket
  type: google-cloud-storage
  source:
    bucket: pcf-ci-data
    versioned_file: terraform/*.json
    json_key: {{google_credentials}}

- name: git-assets
  type: git
  source:
    branch: master
    uri: https://github.com/Logimethods/logilabs-ops.git
 
jobs:
  - name: terraform-gcp
    public: true
    plan:
      - get: gcp-bucket
        trigger: true
      - get: git-assets
        trigger: true
      - task: terraform
        file: git-assets/pcf-deployment-ci/pcf-terraform-gcp/ci/tasks/apply-terraform.yml
        params:
          GOOGLE_CREDENTIALS: {{google_credentials}}
          TF_VAR_ssl_cert: {{ssl_cert}}
          TF_VAR_ssl_cert_private_key: {{ssl_cert_private_key}}
      - put: gcp-bucket
        params: { file: git-assets/pcf-deployment-ci/pcf-terraform-gcp/terraform/terraform.tfstate }