---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: igorf211/pcf-terraform
    tag: "latest"
inputs:
- name: git-assets

params:
  project_id:
  private_key_id:
  bosh_password: admin
  
run:
  path: git-assetss/pcf-deployment-ci/pcf-terraform-gcp/ci/tasks/apply-terraform-script
