---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: igorf211/pcf-terraform
    tag: "latest"
inputs:
- name: git-assets

params:
  GOOGLE_CREDENTIALS:
  TF_VAR_ssl_cert:
  TF_VAR_ssl_cert_private_key:
  gs_secret_access_key:
  gs_access_key_id:
  default_project_id:
  action:
  
run:
  path: git-assets/pcf-deployment-ci/pcf-terraform-gcp/ci/tasks/apply-terraform-script
